### ISSUE TITLE
Compiling the JPEG_file_loader example for windows simulator throws Errors.

### ISSUE THREAD

**Issue by 1337AD** [draupnergraphics/touchgfx-open-repository#19]
Hi,
I tried to compile the JPEG_file_loader example in my touchgfx/4.8.0/app/example folder (like explained in the readme file).
It also compiles files from the touchgfx/framework/source/ folder. In ../platform/driver/touch/SDL2TouchController.cpp it gives me a fatal error: SDL2/SDL_video.h: no such file or directory - as well as render.h: No such file or directory

Do you have an idea whats going on there?

**Comment by zrrbite** [comment]
This was fixed in a4a2cdd92b8e2ee0f36c97ba053579b0acdcb9bc.
