### ISSUE TITLE
stuck at backPorchExited()

### ISSUE THREAD

**Issue by llantalan** [draupnergraphics/touchgfx-open-repository#20]
When I attempt to implement the widget, Application.exe triggers a breakpoint. Error occurs in backPorchExited() in HAL.hpp:

Expression: CanvasWidgetRenderer::hasBuffer() && "No buffer allocated for CanvasWidgetRenderer drawing"

**Comment by zrrbite** [comment]
For applications that use a CanvasWidgetRenderer you must define a canvas buffer, e.g. as follows: You can have a look at the canvas setup in some of the sample applications (app/example/canvas_widget_example, for instance):

 #define CANVAS_BUFFER_SIZE (3600) // In bytes
  static uint8_t canvasBuffer[CANVAS_BUFFER_SIZE];
 CanvasWidgetRenderer::setupBuffer(canvasBuffer, CANVAS_BUFFER_SIZE);
